#! /bin/bash

cd pipeline
cargo build --bin 2dmaskdetermination --release
cargo build --bin 2dorderextraction --release
cargo build --bin 1dflatrelativeorderextraction --release
cargo build --bin biassubtraction --release
cargo build --bin fitetalonpeaks --release
cd ..
