stages:
  master bias:
    cmd: python python/masterBias.py
    deps:
        - python/masterBias.py
        - python/pipeline.py
    params:
        - rawBiasImage.path
        - rawBiasImage.outpath
    outs:
        - ${rawBiasImage.outpath}
  master flat:
    cmd: python python/masterFlat.py
    deps:
        - Data/ProcessedData/MasterBias
            - python/masterFlat.py
                - python/pipeline.py
    params:
        - rawFlatImage.path
        - rawFlatImage.outpath
        - rawBiasImage.outpath
    outs:
        - ${rawFlatImage.outpath}
  bias subtraction:
    cmd: ./pipeline/target/release/biassubtraction
    deps:
        - Data/ProcessedData/MasterBias
    params:
        - rawScienceImage.path
        - rawScienceImage.outpath
        - rawBiasImage.outpath
    outs:
        - Data/ProcessedData/BiasCorrectedScience/20230614
  2D mask determination:
    cmd: ./pipeline/target/release/2dmaskdetermination
    deps:
        - Data/ProcessedData/MasterFlat
    params:
        - rawFlatImage.outpath
        - orderImage.maskOutpath
    outs:
        - ${orderImage.maskOutpath}
  2D order extraction:
    cmd: ./pipeline/target/release/2dorderextraction
    deps:
        - Data/ProcessedData/ExtractedOrders/Mask
        - Data/ProcessedData/BiasCorrectedScience
    params:
        - orderImage.maskOutpath
        - rawScienceImage.outpath
    outs:
        - Data/ProcessedData/ExtractedOrders/Science/20230614
  1D flat-relative order extraction:
    cmd: ./pipeline/target/release/1dflatrelativeorderextraction
    deps:
        - Data/ProcessedData/ExtractedOrders/Science
        - Data/ProcessedData/ExtractedOrders/Mask
    params:
        - orderImage.maskOutpath
        - orderImage.scienceOutpath
    outs:
        - ${optimalOrderExtraction.outpath}
