stages:
  master bias:
    cmd: python python/masterBias.py
    deps:
        - python/masterBias.py
        - python/pipeline.py
    params:
        - MasterBiasImage.inputpath
        - MasterBiasImage.outputpath
    outs:
        - ${MasterBiasImage.outputpath}
  master flat:
    cmd: python python/masterFlat.py
    deps:
        - Data/ProcessedData/MasterBias
        - python/masterFlat.py
        - python/pipeline.py
    params:
        - MasterFlatImage.inputpath
        - MasterFlatImage.outputpath
        - MasterBiasImage.outputpath
    outs:
        - ${MasterFlatImage.outputpath}
  master ThAr:
    cmd: python python/masterThAr.py
    deps:
        - Data/ProcessedData/masterThAr
        - python/masterThAr.py
    params:
        - MasterThArImage.inputpath
        - MasterThArImage.outputpath
        - MasterBiasImage.outputpath
    outs:
        - ${MasterThArImage.outputpath}
  bias subtraction:
    cmd: python python/biasCorrectedScienceImage.py
    deps:
        - Data/ProcessedData/MasterBias
    params:
        - CalibratedScienceImage.inputpath
        - CalibratedScienceImage.outputpath
        - MasterBiasImage.outputpath
  2D mask determination:
    cmd: ./pipeline/target/release/2dmaskdetermination
    deps:
        - Data/ProcessedData/MasterFlat
    params:
        - MasterFlatImage.outputpath
        - OrderImage.maskOutputpath
    outs:
        - ${OrderImage.maskOutputpath}
  2D order extraction:
    cmd: ./pipeline/target/release/2dorderextraction
    deps:
        - Data/ProcessedData/ExtractedOrders/Mask
        - Data/ProcessedData/BiasSubtractedScience
    params:
        - OrderImage.maskOutputpath
        - CalibratedScienceImage.outputpath
  1D flat-relative order extraction:
    cmd: ./pipeline/target/release/1dflatrelativeorderextraction
    deps:
        - Data/ProcessedData/ExtractedOrders/Mask
    params:
        - OrderImage.maskOutputpath
        - OrderImage.scienceOutputpath
  Etalon peaks fitting:
    cmd: ./pipeline/target/release/fitetalonpeaks
    deps:
        - Data/ProcessedData/OptimalExtraction/ 
    params:
        -  EtalonPeakFitting.outputpath

