stages:
  master bias:
    cmd: python python/masterBias.py
    deps:
        - python/masterBias.py
        - python/pipeline.py
    params:
        - rawBiasImage.path
        - rawBiasImage.outputpath
    outs:
        - ${rawBiasImage.outputpath}
  master flat:
    cmd: python python/masterFlat.py
    deps:
        - Data/ProcessedData/MasterBias
        - python/masterFlat.py
        - python/pipeline.py
    params:
        - rawFlatImage.path
        - rawFlatImage.outputpath
        - rawBiasImage.outputpath
    outs:
        - ${rawFlatImage.outputpath}
  bias subtraction:
    cmd: ./pipeline/target/release/biassubtraction
    deps:
        - Data/ProcessedData/MasterBias
    params:
        - rawScienceImage.path
        - rawScienceImage.outputpath
        - rawBiasImage.outputpath
  2D mask determination:
    cmd: ./pipeline/target/release/2dmaskdetermination
    deps:
        - Data/ProcessedData/MasterFlat
    params:
        - rawFlatImage.outputpath
        - orderImage.maskOutputpath
    outs:
        - ${orderImage.maskOutputpath}
  2D order extraction:
    cmd: ./pipeline/target/release/2dorderextraction
    deps:
        - Data/ProcessedData/ExtractedOrders/Mask
        - Data/ProcessedData/BiasSubtractedScience
    params:
        - orderImage.maskOutputpath
        - rawScienceImage.outputpath
  1D flat-relative order extraction:
    cmd: ./pipeline/target/release/1dflatrelativeorderextraction
    deps:
        - Data/ProcessedData/ExtractedOrders/Science
        - Data/ProcessedData/ExtractedOrders/Mask
    params:
        - orderImage.maskOutputpath
        - orderImage.scienceOutputpath

