stages:
  master bias:
    cmd: python masterBias.py
    deps:
    - masterBias.py
    - pipeline.py
    params:
    - rawBiasImage.path
    - rawBiasImage.outpath
    outs:
    - ${rawBiasImage.outpath}
  master flat:
    cmd: python masterFlat.py
    deps:
    - Data/ProcessedData/MasterBias
    - masterFlat.py
    - pipeline.py
    params:
    - rawFlatImage.path
    - rawFlatImage.outpath
    - rawBiasImage.outpath
    outs:
    - ${rawFlatImage.outpath}
  calibrated science:
    cmd: python biasCorrectedScienceImage.py
    deps:
    - Data/ProcessedData/MasterBias
    - biasCorrectedScienceImage.py
    - pipeline.py
    params:
    - rawScienceImage.path
    - rawScienceImage.outpath
    - rawBiasImage.outpath
    outs:
    - ${rawScienceImage.outpath}
  order mask extraction:
    cmd: python orderMaskExtraction.py
    deps:
    - pipeline.py
    - Data/ProcessedData/MasterFlat
    params:
    - rawFlatImage.outpath
    - orderMaskImage.outpath
    outs:
    - ${orderMaskImage.outpath}
  order science extraction:
    cmd: python orderScienceExtraction.py
    deps:
    - pipeline.py
    - Data/ProcessedData/ExtractedOrders/Mask
    - Data/ProcessedData/BiasCorrectedScience
    params:
    - orderMaskImage.outpath
    - rawScienceImage.outpath
    outs:
    - ${orderScienceExtraction.outpath}
    
