stages:
    master bias:
        cmd: python python/masterBias.py
        deps:
            - python/masterBias.py
            - python/pipeline.py
        params:
            - Configuration.rootFolderProcessedData
            - MasterBiasImage.inputPath
            - MasterBiasImage.outputPath
        outs:
          - ${Configuration.rootFolderProcessedData}/${MasterBiasImage.outputPath}

    master dark:
        cmd: python python/masterDark.py
        deps:
            - python/masterDark.py
            - python/pipeline.py
        params:
            - Configuration.rootFolderProcessedData
            - MasterDarkImage.inputPath
            - MasterDarkImage.outputPath
        outs:
            - ${Configuration.rootFolderProcessedData}/${MasterDarkImage.outputPath}
  
    master flat:
        cmd: python python/masterFlat.py
        deps:
            - Data/ProcessedData/MasterBias
            - Data/ProcessedData/MasterDark
            - python/masterFlat.py
            - python/pipeline.py
        params:
            - Configuration.rootFolderProcessedData
            - MasterFlatImage.inputPath
            - MasterFlatImage.outputPath
            - MasterBiasImage.outputPath
            - MasterDarkImage.outputPath
        outs:
            - ${Configuration.rootFolderProcessedData}/${MasterFlatImage.outputPath}
  
    master ThAr:
        cmd: python python/masterThAr.py
        deps:
            - Data/ProcessedData/masterBias
            - Data/ProcessedData/MasterDark
            - python/masterThAr.py
        params:
            - Configuration.rootFolderProcessedData
            - MasterThArImage.inputPath
            - MasterThArImage.outputPath
            - MasterBiasImage.outputPath
            - MasterDarkImage.outputPath
        outs:
            - ${Configuration.rootFolderProcessedData}/${MasterThArImage.outputPath}
  
    bias and dark subtraction:
       cmd: python python/biasAndDarkCorrection.py
       deps:
            - Data/ProcessedData/MasterBias
            - Data/ProcessedData/MasterDark
       params:
            - Configuration.rootFolderProcessedData
            - BiasAndDarkSubtractedScienceImage.inputPath
            - BiasAndDarkSubtractedScienceImage.outputPath
            - MasterBiasImage.outputPath
            - MasterDarkImage.outputPath
  
    2D order mask determination:
        cmd: ./pipeline/target/release/2dmaskdetermination
        deps:
            - pipeline/src/bin/2dmaskdetermination.rs
            - Data/ProcessedData/MasterFlat
        params:
            - Configuration.rootFolderProcessedData
            - TwoDimensionalOrderMaskTracing.inputPath
            - TwoDimensionalOrderMaskTracing.outputPath
            - TwoDimensionalOrderMaskTracing.outputPathSmoothedMasterFlat
        outs:
            - ${Configuration.rootFolderProcessedData}/${TwoDimensionalOrderMaskTracing.outputPath}
            - ${Configuration.rootFolderProcessedData}/${TwoDimensionalOrderMaskTracing.outputPathSmoothedMasterFlat}
  
    2D order mask visualization:
        cmd: python python/mask_fits_image.py
        params: 
            - Configuration.rootFolderProcessedData
            - TwoDimensionalOrderMaskTracing.outputPath
        outs:
            - ${Configuration.rootFolderProcessedData}/${TwoDimensionalOrderMaskVisualisation.outputPath}
  
    1D flat-relative order extraction:
        cmd: ./pipeline/target/release/1dflatrelativeorderextraction
        deps:
            - pipeline/src/bin/1dflatrelativeorderextraction.rs
            - Data/ProcessedData/OrderMask 
        params:
            - Configuration.rootFolderProcessedData
            - TwoDimensionalOrderMaskTracing.outputPath
  
    # Etalon peaks fitting:
    #     cmd: ./pipeline/target/release/fitetalonpeaks
    #     deps:
    #         - Data/ProcessedData/OptimalExtraction/ 
    #     params:
    #         - Configuration.rootFolderProcessedData
    #         - EtalonPeakFitting.inputPath
    #         - EtalonPeakFitting.outputPath
    #         - OptimalOrderExtraction.outputPath

