configuration:
        rootFolder: /home/driess/Projects/MARVELpipeline/
rawBiasImage:
        path: [Data/RawData/CalibrationImages/Bias/20230504T135640_BBBBB_H_0000.fits,  Data/RawData/CalibrationImages/Bias/20230504T135642_BBBBB_H_0000.fits,  Data/RawData/CalibrationImages/Bias/20230504T135644_BBBBB_H_0000.fits,  Data/RawData/CalibrationImages/Bias/20230504T135648_BBBBB_H_0000.fits,  Data/RawData/CalibrationImages/Bias/20230504T135652_BBBBB_H_0000.fits]
        outpath: Data/ProcessedData/MasterBias/testsXXXBias.fits
rawFlatImage:
        path: [Data/RawData/CalibrationImages/Flat/20230504T142007_FFFFF_H_0001.fits,Data/RawData/CalibrationImages/Flat/20230504T142402_FFFFF_H_0001.fits,Data/RawData/CalibrationImages/Flat/20230504T142759_FFFFF_H_0001.fits,Data/RawData/CalibrationImages/Flat/20230504T143157_FFFFF_H_0001.fits,Data/RawData/CalibrationImages/Flat/20230504T143554_FFFFF_H_0001.fits]
        outpath: Data/ProcessedData/MasterFlat/testsXXXFlat.fits
rawScienceImage:
        path: Data/RawData/ScienceFrames/20221027T175106_TSSSS_H_0900.fits
        outpath: Data/ProcessedData/BiasCorrectedScience/testsXXXScience.fits
orderMaskImage:
        smoothMasterFlat: Data/ProcessedData/MasterFlat/smoothed_masterflat.fits
        outpath: Data/ProcessedData/ExtractedOrders/Mask/testsXXXorder.fits
orderScienceExtraction:
        outpath: Data/ProcessedData/ExtractedOrders/Science/testsXXXscienceXXXorders.fits
optimalOrderExtraction:
        outpath: Data/ProcessedData/OptimalExtraction/optimal_extracted_science_flux.fits
