#+title:Changes that still should happen




* Speed up flux-extraction

* Save coordinates, flux, order/fiber 

* in pipeline.py:
- Master flats should taken into account the S/N of each of the flats (cf HERMES pipeline description)


* in tools.py:
- gain/exposureTime/darkRate should be read from fitsFile (if this is in the file)

* Include gain/exposureTime/darkRate in .fits header

* Should use S/N to find the correct #pixels around the polynomial fit to inlcude
Maxize S/N wrp amound of pixels around:
- [ ] where orders is verticall
- [ ] where the value is maximal
- [X] when we are in the middle row

=> Check which one of these gives better results


* (Flat field) Responce of instrument (in horizontal direction)
- Check background between orders and see how they vary, depending on position. This gives a idea of the _responce_ of the detector. (See p.38 of the thesis of Nicholas)
- TODO: At some point, check how much this influences our respults


* Make a README file that explains installing/starting the pipeline


* Include input hash in output fits file

* Thinks about a validation/documentation plan 

* Should extract the bias/readout noise from Master Bias 

* Fitting for flux calibration: statsmodels , https://www.statsmodels.org/stable/index.html 


* Flux Extraction (copied from MAROON_X)

** Etalon (and when needed ThAr) lines need to be fitted to determine the centroid of the 1D extracted spectrum.

1. Etalon linsed need to be fitted to determine their centroid. -> 1D extracted spectrum
   input : -a reduced ethalon_spectrum, -i reduced master_flat, -fs fibers (range or list), -o orders (range or list)

   - orders and fibers from cl. If not given, both are None

2. Etalon lines are unresolved (WHAT DOES THIS MEAN?)
3. 

** Build static wavelenght solution from ThAr and etalon spectra. 
